version: '3.0'
services:
  web:
    image: nginx:latest
    ports:
      - 9000:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data:/data

  db:
    image: postgres:latest
    ports:
      - 5555:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    env_file: '.env'

  cache:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    env_file: '.env'

volumes:
  pg_data:
