version: '3.0'
services:
  web:
    image: nginx:latest
    ports:
      - 9000:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data:/data

  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    env_file: '.env'

  cache:
    image: redis:latest
    restart: always
    env_file: '.env'

  backend:
    build:
      dockerfile: ./dockerization/Dockerfile
    env_file: '.env'
    depends_on:
      - db
      - cache
    restart: on-failure
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    entrypoint:
      - /bin/sh
      - ./start_app.sh

volumes:
  pg_data:
  user_data:
