version: '3.0'
services:
  web:
    image: nginx:latest
    ports:
      - 9000:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data:/data
    depends_on:
      backend:
        condition: service_started
    restart: always

  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    env_file: '.env'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3

  cache:
    image: redis:latest
    restart: always
    env_file: '.env'

  backend:
    build:
      dockerfile: ./dockerization/Dockerfile
    env_file: '.env'
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    restart: on-failure
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    entrypoint:
      - /bin/sh
      - ./start_app.sh

volumes:
  pg_data:
