version: '3.0'
services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data:/data

  db:
    image: postgres:latest
    ports:
      - 5555:5432
    volumes:
      - pg_data:/var/lib/postgres/data
    restart: always
    env_file: '.env'

volumes:
  pg_data:
